CREATE DATABASE MY_DB;


CREATE TABLE REGISTRATION
(
  C_NAME VARCHAR(50),
  USERNAME VARCHAR(50),
  EMAIL VARCHAR(60),
  CONTACT_NUMBER INT,
  PASS NVARCHAR(50)NOT NULL
);

SELECT * FROM REGISTRATION;



CREATE TABLE J_REGISTRATION
(
  NAME VARCHAR(50),
  USERNAME VARCHAR(50),
  EMAIL VARCHAR(60),
  CONTACT_NUMBER INT,
  GENDER VARCHAR(50),
  PASS NVARCHAR(50)NOT NULL
);

SELECT * FROM J_REGISTRATION;



CREATE TABLE COMPANY_DETAILS
(
  COMPANY_NAME VARCHAR(50),
  ID INT PRIMARY KEY,
  JOB_TITLE VARCHAR(50),
  JOB_LOCATION VARCHAR(50),
  CONTACT_NUMBER INT,
  SALARY INT,
  ADD_LOGO IMAGE
);

SELECT * FROM COMPANY_DETAILS;



CREATE TABLE EMPLOYEE_DETAILS
(
  FRIST_NAME VARCHAR(50),
  LAST_NAME VARCHAR(50),
  CURRENT_ADDRESS VARCHAR(500),
  EMAIL_ADDRESS VARCHAR(200),
  CONTACT_NUMBER INT,
  AGE INT,
  GRADUATION VARCHAR(50),
  MASTERS VARCHAR(50),
  OTHERS VARCHAR(50),
  SELECTED_COMPANY VARCHAR(50),
  JOB_POSITION VARCHAR(50),
  PICTURE IMAGE
);

SELECT * FROM EMPLOYEE_DETAILS;



CREATE TABLE MESSAGE_BOX
(
COMMENT VARCHAR(500)
);

SELECT * FROM MESSAGE_BOX;